/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloClientes;

import BO.ClienteBO.ClienteBO;
import Entidades.Clientes.Cliente;
import Entidades.Clientes.ClientesFrecuentes;
import Fabricas.FabricaClientes;
import NegocioException.NegocioException;
import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Font;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alberto Jimenez
 */
public class ReporteClientes extends javax.swing.JFrame {

    private final FormClientesTabla formClientesTabla = new FormClientesTabla();

    /**
     * Creates new form ReporteClientes
     * @throws NegocioException.NegocioException
     */
    public ReporteClientes() throws NegocioException{
        initComponents();
        formClientesTabla.setVisible(true);
        this.pnlFormClientes.add(formClientesTabla);
        getContentPane().setBackground(new Color(0x4dd3e0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filtroTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        filtroCorreo = new javax.swing.JTextField();
        btnFiltro = new javax.swing.JButton();
        pnlFormClientes = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnImprimirReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Reporte Clientes");
        jLabel1.setFont(new Font("Arial", Font.BOLD, 32));

        jLabel3.setText("Teléfono");
        jLabel3.setFont(new Font("Arial", Font.PLAIN, 14));

        jLabel4.setText("Correo Electronico");
        jLabel4.setFont(new Font("Arial", Font.PLAIN, 14));

        btnFiltro.setText("Filtrar");
        btnFiltro.setBackground(new Color(162, 132, 94));
        btnFiltro.setForeground(Color.WHITE);
        btnFiltro.setFont(new Font("Arial", Font.BOLD, 16));
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        pnlFormClientes.setPreferredSize(new java.awt.Dimension(638, 521));
        pnlFormClientes.setLayout(new java.awt.BorderLayout());

        btnSalir.setText("Salir");
        btnSalir.setBackground(new Color(236, 34, 31));
        btnSalir.setForeground(Color.WHITE);
        btnSalir.setFont(new Font("Arial", Font.BOLD, 16));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnImprimirReporte.setText("IMPRIMIR REPORTE");
        btnImprimirReporte.setBackground(new Color(88, 86, 214));
        btnImprimirReporte.setForeground(Color.WHITE);
        btnImprimirReporte.setFont(new Font("Arial", Font.BOLD, 20));
        btnImprimirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271)
                        .addComponent(btnImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(filtroTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtroCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlFormClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtroCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(btnFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(pnlFormClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnImprimirReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        try {
            ClienteBO clienteBO = FabricaClientes.crearClienteBO();

            String telefonoFiltro = filtroTelefono.getText();
            String correoFiltro = filtroCorreo.getText();

            if (telefonoFiltro.isEmpty() && correoFiltro.isEmpty()) {
                formClientesTabla.recargarTabla();
            }

            List<Cliente> clientesFiltrados = clienteBO.filtrarClientesReporte(
                    telefonoFiltro.isEmpty() ? null : telefonoFiltro,
                    correoFiltro.isEmpty() ? null : correoFiltro);
            formClientesTabla.recargarTabla(clientesFiltrados);

        } catch (NegocioException ex) {
            Logger.getLogger(ModuloPrincipalClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFiltroActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnImprimirReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirReporteActionPerformed
        try {
            generarReporteClientesFrecuentes();
        } catch (NegocioException ex) {
            Logger.getLogger(ModuloPrincipalClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirReporteActionPerformed
    
    private void generarReporteClientesFrecuentes() throws NegocioException {
        ClienteBO clienteBO = FabricaClientes.crearClienteBO();
        List<Cliente> clientes = clienteBO.obtenerListaClientesBO();

        Document document = new Document();
        try {
            String ruta = "reporte_clientes_frecuentes.pdf";
            PdfWriter.getInstance(document, new FileOutputStream(ruta));
            document.open();

            document.add(new Paragraph("REPORTE: CLIENTES FRECUENTES"));
            document.add(new Paragraph(" "));

            PdfPTable tabla = new PdfPTable(6);
            tabla.setWidthPercentage(100);

            // Encabezados
            tabla.addCell("Nombre");
            tabla.addCell("Correo");
            tabla.addCell("Teléfono");
            tabla.addCell("Fecha Registro");
            tabla.addCell("Puntos");
            tabla.addCell("Total Gastado");

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

            for (Cliente c : clientes) {
                if (c instanceof ClientesFrecuentes) {
                    ClientesFrecuentes cf = (ClientesFrecuentes) c;

                    tabla.addCell(cf.getNombre());
                    tabla.addCell(cf.getCorreo() != null ? cf.getCorreo() : "");
                    tabla.addCell(cf.getNumTelefono());
                    tabla.addCell(cf.getFechaRegistro() != null
                            ? sdf.format(cf.getFechaRegistro().getTime())
                            : "");
                    tabla.addCell(String.valueOf(cf.getPuntos()));
                    tabla.addCell(String.valueOf(cf.getTotalGastado()));
                }
            }

            document.add(tabla);
            document.close();

            JOptionPane.showMessageDialog(this, "Reporte generado con éxito: " + ruta);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el PDF");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnImprimirReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField filtroCorreo;
    private javax.swing.JTextField filtroTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlFormClientes;
    // End of variables declaration//GEN-END:variables
}
