/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloComandas.AñadirComanda;

import ModuloClientes.FormClientesTabla;
import ModuloComandas.AñadirComanda.AñadirComanda;
import NegocioException.NegocioException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;

/**
 *
 * @author PC Gamer
 */
public class AñadirClienteComanda extends javax.swing.JFrame {
    private FormClientesTabla formClientesTabla = new FormClientesTabla();
    private AñadirComanda añadirComanda;

    /**
     * Creates new form AñadirClienteComanda
     * @param añadirComanda
     * @throws NegocioException.NegocioException
     */
public AñadirClienteComanda(AñadirComanda añadirComanda) throws NegocioException {
    initComponents();
    this.añadirComanda = añadirComanda;
    this.pnlTablaClientes.add(formClientesTabla);
    formClientesTabla.setVisible(true);
    clickearTabla();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeleccionarCliente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlTablaClientes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSeleccionarCliente.setBackground(new java.awt.Color(204, 255, 204));
        btnSeleccionarCliente.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnSeleccionarCliente.setText("Doble Click para Seleccionar Cliente");
        btnSeleccionarCliente.setEnabled(false);
        btnSeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarClienteActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlTablaClientes.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTablaClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnSeleccionarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSeleccionarCliente))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarClienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
     
private void clickearTabla() {
    formClientesTabla.getTablabaClientes().addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                JTable tabla = formClientesTabla.getTablabaClientes();
                int fila = tabla.getSelectedRow();
                if (fila >= 0) {
                    String nombreCliente = tabla.getValueAt(fila, 0).toString();
                    añadirComanda.setNombreCliente(nombreCliente);
                    añadirComanda.getTxtClienteSeleccionadoNombre().setText(nombreCliente);
                    dispose();
                }
            }
        }
    });
}


    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionarCliente;
    private javax.swing.JPanel pnlTablaClientes;
    // End of variables declaration//GEN-END:variables
}
