/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloProductos.AñadirProducto;

import ModuloIngredientes.FormIngredientesTabla;
import NegocioException.NegocioException;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC Gamer
 */
public class AgregarIngredienteAListaProductoNuevo extends javax.swing.JFrame {
    FormIngredientesTabla formIngredientesTabla = new FormIngredientesTabla();
    JTable TblTablaIngredientesHastaElMomento;
    
    /**
     * Creates new form AgregarIngredienteAProducto
     * @throws NegocioException.NegocioException
     */
    public AgregarIngredienteAListaProductoNuevo(JTable tblTablaIngredientesHastaElMomento) throws NegocioException {
        initComponents();
        
        this.TblTablaIngredientesHastaElMomento = tblTablaIngredientesHastaElMomento;
        pnlIngredientesChilos.add(formIngredientesTabla);
        pnlIngredientesChilos.setVisible(true);
        getContentPane().setBackground(new Color(0x78f332));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIngredientesChilos = new javax.swing.JPanel();
        btnConfirmarIngrediente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar ingrediente a producto");

        pnlIngredientesChilos.setLayout(new java.awt.BorderLayout());

        btnConfirmarIngrediente.setBackground(new java.awt.Color(204, 255, 204));
        btnConfirmarIngrediente.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnConfirmarIngrediente.setText("Agregar Ingrediente");
        btnConfirmarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarIngredienteActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIngredientesChilos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnConfirmarIngrediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlIngredientesChilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 446, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmarIngrediente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarIngredienteActionPerformed
       
            JTable tablaIngredientes = formIngredientesTabla.getTablaIngredientes();

    int filaSeleccionada = tablaIngredientes.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona un ingrediente.");
        return;
    }

    String nombre = tablaIngredientes.getValueAt(filaSeleccionada, 0).toString();
    String unidad = tablaIngredientes.getValueAt(filaSeleccionada, 1).toString();

    String inputCantidad = JOptionPane.showInputDialog(this, "Ingresa la cantidad necesaria:");
    
    if (inputCantidad == null || inputCantidad.isBlank()) {
        JOptionPane.showMessageDialog(this, "Cantidad inválida.");
        return;
    }

    double cantidad;
    try {
        cantidad = Double.parseDouble(inputCantidad);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Cantidad debe ser un número.");
        return;
    }


    DefaultTableModel modeloHastaAhora = (DefaultTableModel) TblTablaIngredientesHastaElMomento.getModel();

        for (int i = 0; i < modeloHastaAhora.getRowCount(); i++) {
            String nombreExistente = modeloHastaAhora.getValueAt(i, 0).toString();
            if (nombreExistente.equalsIgnoreCase(nombre)) {
                JOptionPane.showMessageDialog(this, "Este ingrediente ya fue agregado.");
                return;
            }
        }

    
    
    Object[] filaNueva = { nombre, unidad, cantidad };
    modeloHastaAhora.addRow(filaNueva);

    JOptionPane.showMessageDialog(this, "Ingrediente agregado correctamente.");
    this.dispose(); 
        
        
        
    }//GEN-LAST:event_btnConfirmarIngredienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarIngrediente;
    private javax.swing.JPanel pnlIngredientesChilos;
    // End of variables declaration//GEN-END:variables
}
