/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModuloProductos;

import BO.ProductoBO.ProductoBO;
import Entidades.Productos.Producto;
import Fabricas.FabricaProductos;
import NegocioException.NegocioException;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC Gamer
 */
public class FormProductosTablaTodos extends javax.swing.JPanel {

    /**
     * Creates new form FormProductosTablaTodos
     * @throws NegocioException.NegocioException
     */
    public FormProductosTablaTodos() throws NegocioException {
        initComponents();
        cargarProductosEnTablaTodos();
        
    }

        private void cargarProductosEnTablaTodos() throws NegocioException {
        
        ProductoBO productoBO = FabricaProductos.crearProductoBO();
        String[] columnas = {"Nombre", "Precio", "Tipo" , "Disponible"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0){
           
            @Override
            public boolean isCellEditable(int row, int column) {
            return false; 
        }
        };
 
        List<Producto> productos = productoBO.mostrarListaProductosTodosBO();

        for (Producto pro : productos) {
            Object[] fila = {
                pro.getNombre(),
                pro.getPrecio(),
                pro.getTipo(),
                pro.getEstado()
                };
            modeloTabla.addRow(fila);
        }

    tblProductos.setModel(modeloTabla);
}
        
        public void cargarProductosEnTablaTodosExterno() throws NegocioException{
            cargarProductosEnTablaTodos();
        }
        
        
        
    public void llenarTablaFiltrada(List<Producto> productos) {
        String[] columnas = {"Nombre", "Precio", "Tipo", "Disponible"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for (Producto pro : productos) {
            Object[] fila = {
                pro.getNombre(),
                pro.getPrecio(),
                pro.getTipo(),
                pro.getEstado()
            };
            modeloTabla.addRow(fila);
        }
        
        tblProductos.setModel(modeloTabla);
    }

    public JTable getTblProductos() {
        return tblProductos;
    }

        
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScrollPane.setViewportView(tblProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JScrollPane)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    public javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
