/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModuloProductos;

import BO.IngredienteBO.IngredienteBO;
import BO.ProductoBO.ProductoBO;
import Entidades.Ingredientes.Ingrediente;
import Entidades.Productos.Producto;
import Fabricas.FabricaIngredientes;
import Fabricas.FabricaProductos;
import NegocioException.NegocioException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC Gamer
 */
public class FormProductosTablaDisponibles extends javax.swing.JPanel {

    /**
     * Creates new form FormProductosTabla
     */
    public FormProductosTablaDisponibles() throws NegocioException {
        initComponents();
        cargarProductosEnTablaDisponibles();
    }

    private void cargarProductosEnTablaDisponibles() throws NegocioException {
        
        ProductoBO productoBO = FabricaProductos.crearProductoBO();
        String[] columnas = {"Nombre", "Precio", "Tipo"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0){
           
            @Override
            public boolean isCellEditable(int row, int column) {
            return false; 
        }
        };
 
        List<Producto> productos = productoBO.filtrarPorNombreProductoDisponiblesBO("");

        for (Producto pro : productos) {
            Object[] fila = {
                pro.getNombre(),
                pro.getPrecio(),
                pro.getTipo()
                };
            modeloTabla.addRow(fila);
        }

    tblProductos.setModel(modeloTabla);
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblProductos.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
