/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModuloIngredientes;

import BO.IngredienteBO.IngredienteBO;
import Entidades.Ingredientes.Ingrediente;
import Fabricas.FabricaIngredientes;
import NegocioException.NegocioException;
import java.awt.Color;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC Gamer
 */
public class FormIngredientesTabla extends javax.swing.JPanel {

    /**
     * Creates new form FomIngredientesTabla
     * @throws NegocioException.NegocioException
     */
    public FormIngredientesTabla() throws NegocioException {
        initComponents();
        cargarIngredientesEnTabla();
    }


    
    
    private void cargarIngredientesEnTabla() throws NegocioException {
        
        IngredienteBO ingredienteBO = FabricaIngredientes.crearIngredienteBO();
        String[] columnas = {"Nombre", "Unidad de Medida", "Stock"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0){
           
            @Override
            public boolean isCellEditable(int row, int column) {
            return false; 
        }
        };
 
        List<Ingrediente> ingredientes = ingredienteBO.obtenerListaIngredientesBO();

        for (Ingrediente ing : ingredientes) {
            Object[] fila = {
                ing.getNombre(),
                ing.getUnidad_medida(),
                ing.getStock()
                };
            modeloTabla.addRow(fila);
        }

    tblIngredientes.setModel(modeloTabla);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();

        tblIngredientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Unidad De Medida", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIngredientes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblIngredientes);
        if (tblIngredientes.getColumnModel().getColumnCount() > 0) {
            tblIngredientes.getColumnModel().getColumn(0).setResizable(false);
            tblIngredientes.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblIngredientes.getColumnModel().getColumn(1).setResizable(false);
            tblIngredientes.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblIngredientes.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTablaIngredientes() {
        return tblIngredientes;
    }
    
    public void recargarTabla() throws NegocioException {
        cargarIngredientesEnTabla();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIngredientes;
    // End of variables declaration//GEN-END:variables
}
